FROM node:lts-alpine as builder

WORKDIR /usr/src/app

COPY ./package*.json  /usr/src/app/

RUN npm install 

COPY ./ /usr/src/app/

RUN npm run build

FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
