version: "3"

services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    networks:
      - proxy-front
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  proxy-front:
    driver: bridge
